/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package claseDatosSensor;


/**
 *
 * @author Justin Rodriguez Gonzalez
 */
public class Filtro extends javax.swing.JDialog {
    private String[] datos = {"", "", "", "", ""};
    private boolean confirmar;
    /**
     * Creates new form Filtro
     */
    public Filtro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(parent);
        this.confirmar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        ckIdentificador = new javax.swing.JCheckBox();
        ckFecha = new javax.swing.JCheckBox();
        ckHora = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtIdenficador = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ckIdentificador.setBackground(new java.awt.Color(255, 255, 255));
        ckIdentificador.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        ckIdentificador.setForeground(new java.awt.Color(255, 255, 255));
        ckIdentificador.setText("Identificador Sensor");
        ckIdentificador.setBorder(null);
        ckIdentificador.setContentAreaFilled(false);
        ckIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckIdentificadorActionPerformed(evt);
            }
        });
        pPrincipal.add(ckIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 40));

        ckFecha.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        ckFecha.setForeground(new java.awt.Color(255, 255, 255));
        ckFecha.setText("Fecha");
        ckFecha.setBorder(null);
        ckFecha.setContentAreaFilled(false);
        ckFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckFechaActionPerformed(evt);
            }
        });
        pPrincipal.add(ckFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 210, 40));

        ckHora.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        ckHora.setForeground(new java.awt.Color(255, 255, 255));
        ckHora.setText("Hora");
        ckHora.setContentAreaFilled(false);
        ckHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckHoraActionPerformed(evt);
            }
        });
        pPrincipal.add(ckHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 210, 40));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar");
        pPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 90, 60));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (8).png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pPrincipal.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 290, 80));

        txtIdenficador.setBackground(new java.awt.Color(240, 237, 255));
        txtIdenficador.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtIdenficador.setBorder(null);
        txtIdenficador.setEnabled(false);
        pPrincipal.add(txtIdenficador, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 320, 40));

        txtFecha.setBackground(new java.awt.Color(240, 237, 255));
        txtFecha.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtFecha.setBorder(null);
        txtFecha.setEnabled(false);
        pPrincipal.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 320, 40));

        txtHora.setBackground(new java.awt.Color(240, 237, 255));
        txtHora.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtHora.setForeground(new java.awt.Color(240, 237, 255));
        txtHora.setBorder(null);
        txtHora.setEnabled(false);
        pPrincipal.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 320, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/txtField2.png"))); // NOI18N
        pPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 380, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/txtField2.png"))); // NOI18N
        pPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 380, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/txtField2.png"))); // NOI18N
        pPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 380, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (7).png"))); // NOI18N
        pPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 640));

        getContentPane().add(pPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        datos[0] = (this.txtIdenficador.isEnabled()) ? this.txtIdenficador.getText() : "";
        datos[1] = (this.txtFecha.isEnabled()) ? this.txtFecha.getText() : "";
        datos[2] = (this.txtHora.isEnabled()) ? this.txtHora.getText() : "";

        this.confirmar = true;
        this.setVisible(false);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void ckIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckIdentificadorActionPerformed
        this.txtIdenficador.setEnabled((this.txtIdenficador.isEnabled()) ? false : true);
    }//GEN-LAST:event_ckIdentificadorActionPerformed

    private void ckFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckFechaActionPerformed
       this.txtFecha.setEnabled((this.txtFecha.isEnabled()) ? false : true);
    }//GEN-LAST:event_ckFechaActionPerformed

    private void ckHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckHoraActionPerformed
       this.txtHora.setEnabled((this.txtHora.isEnabled()) ? false : true);
    }//GEN-LAST:event_ckHoraActionPerformed

    public boolean confirmacion() {
        return this.confirmar;
    }
    
     public String getDatos(int indice) {
        return datos[indice];
    }

    public boolean getCkFecha() {
        return this.ckFecha.isSelected();
    }

    public boolean getCkHora() {
        return this.ckHora.isSelected();
    }

    public boolean getCkIdentificador() {
        return this.ckIdentificador.isSelected();
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JCheckBox ckFecha;
    private javax.swing.JCheckBox ckHora;
    private javax.swing.JCheckBox ckIdentificador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdenficador;
    // End of variables declaration//GEN-END:variables
}
