/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package claseDatosSensor;

import com.jefte.estacionmeteorologica.claseSensor.Sensor;
import com.fasterxml.jackson.core.type.TypeReference;
import com.jefte.estacionmeteorologica.ManejoArchivos.JsonHandler;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Justin Rodriguez Gonzalez
 */
public class FormularioDatosSensor extends javax.swing.JDialog {

    private boolean edicion;
    private boolean confirmar;
    private JsonHandler<Sensor> gestionSensor;
    private JsonHandler<DatosSensor> gestionDatosSensor;
    private String nombreJsonSensores = "sensores.json";

    /**
     * Creates new form FormularioDatosSensor
     */
    public FormularioDatosSensor(java.awt.Frame parent, boolean modal, String nombreDatosSensores, DatosSensor datosSensor) {
        super(parent, modal);
        initComponents();
        this.gestionSensor = new JsonHandler(nombreJsonSensores, new TypeReference<Map<Integer, Sensor>>() {
        });
        this.gestionDatosSensor = new JsonHandler(nombreDatosSensores, new TypeReference<Map<Integer, DatosSensor>>() {
        });
        llenarCBX();

    }


    public boolean confirmacion() {
        return this.confirmar;
    }

    private void llenarCBX() {
        for (Sensor sensor : this.gestionSensor.obtenerDatos().values()) {
            this.cbxIdSensores.addItem(sensor.getIdentificador());
        }
    }

    private void iniciar() {
        if (!this.cbxIdSensores.getSelectedItem().equals("Elegir")) {
            this.confirmar = true;
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Debe de elegir una opcion");
        }
    }

    public DatosSensor consultarTarea() {
        return new DatosSensor(
                gestionDatosSensor.obtenerUltimoId() + 1,
                1,
                this.cbxIdSensores.getSelectedItem().toString()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxIdSensores = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pPrincipal.setBackground(new java.awt.Color(240, 237, 255));
        pPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sensores Registrados");
        pPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, 30));

        cbxIdSensores.setBackground(new java.awt.Color(240, 237, 255));
        cbxIdSensores.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        cbxIdSensores.setForeground(new java.awt.Color(0, 0, 0));
        cbxIdSensores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir" }));
        cbxIdSensores.setBorder(null);
        pPrincipal.add(cbxIdSensores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 320, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/txtField2.png"))); // NOI18N
        pPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 380, 80));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Guardar");
        pPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 80, 40));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Volver");
        pPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 80, 40));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (8).png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pPrincipal.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 190, 60));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (8).png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pPrincipal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 190, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (7).png"))); // NOI18N
        pPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 500, 420));

        getContentPane().add(pPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 423));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.confirmar = false;
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        iniciar();
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxIdSensores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pPrincipal;
    // End of variables declaration//GEN-END:variables
}
