/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.jefte.estacionmeteorologica.Roles;

import com.fasterxml.jackson.core.type.TypeReference;
import com.jefte.estacionmeteorologica.ManejoArchivos.JsonHandler;
import java.util.Map;

/**
 *
 * @author Brandon Campos
 */
public class GUIAgregarRol extends javax.swing.JDialog {

    /**
     * Creates new form GUIAgregarRol
     */
    private boolean edicion;
    private boolean confirmar;
    private JsonHandler<Rol> gestionRol;


    public GUIAgregarRol(java.awt.Frame parent, boolean modal, Rol rol, String nombreJson) {
        super(parent, modal);
        this.gestionRol = new JsonHandler(nombreJson, new TypeReference<Map<Integer, Rol>>() {
        });

        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        cbxPermisoReportes = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxPermisoDatosRol = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxPermisoDatosUsuario = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxPermisoDatosEnVivo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxPermisoDatoSensor = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxPermisoSensores = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cancelar");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 70, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (8).png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setFocusable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 160, 50));

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Guardar");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (8).png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 160, 50));

        cbxPermisoReportes.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoReportes.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "False", "True" }));
        cbxPermisoReportes.setBorder(null);
        cbxPermisoReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPermisoReportesActionPerformed(evt);
            }
        });
        jPanel2.add(cbxPermisoReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 250, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 290, 50));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reportes:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        cbxPermisoDatosRol.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoDatosRol.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoDatosRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "False", "True" }));
        cbxPermisoDatosRol.setBorder(null);
        cbxPermisoDatosRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPermisoDatosRolActionPerformed(evt);
            }
        });
        jPanel2.add(cbxPermisoDatosRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 260, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 290, 50));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Datos Rol: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        cbxPermisoDatosUsuario.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoDatosUsuario.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoDatosUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "False", "True" }));
        cbxPermisoDatosUsuario.setBorder(null);
        cbxPermisoDatosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPermisoDatosUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(cbxPermisoDatosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 260, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 300, 50));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Datos Usuario:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        cbxPermisoDatosEnVivo.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoDatosEnVivo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoDatosEnVivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "False", "True" }));
        cbxPermisoDatosEnVivo.setBorder(null);
        cbxPermisoDatosEnVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPermisoDatosEnVivoActionPerformed(evt);
            }
        });
        jPanel2.add(cbxPermisoDatosEnVivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 260, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 290, 50));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Datos en Vivo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos Sensores:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, -1));

        cbxPermisoDatoSensor.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoDatoSensor.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoDatoSensor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "False", "True" }));
        cbxPermisoDatoSensor.setBorder(null);
        jPanel2.add(cbxPermisoDatoSensor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 240, 30));

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 300, 50));

        txtNombre.setBackground(new java.awt.Color(240, 237, 255));
        txtNombre.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtNombre.setBorder(null);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 260, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 330, 50));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sensores:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        cbxPermisoSensores.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoSensores.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoSensores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "False", "True" }));
        cbxPermisoSensores.setBorder(null);
        jPanel2.add(cbxPermisoSensores, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 240, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 300, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (7).png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 670));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 330, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 330, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.confirmar = true;
        this.setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.confirmar = false;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxPermisoReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPermisoReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPermisoReportesActionPerformed

    private void cbxPermisoDatosEnVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPermisoDatosEnVivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPermisoDatosEnVivoActionPerformed

    private void cbxPermisoDatosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPermisoDatosUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPermisoDatosUsuarioActionPerformed

    private void cbxPermisoDatosRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPermisoDatosRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPermisoDatosRolActionPerformed
    public void guardarDatos(Rol rol) {

        if (rol != null) {
            this.txtNombre.setText(rol.getNombre());
            this.edicion = true;
        }

        this.edicion = false;

    }

    public boolean confirmacion() {

        return this.confirmar;

    }

    public Rol consultarTarea() {
        return new Rol(
                gestionRol.obtenerUltimoId()+1,
                this.txtNombre.getText(),
                Boolean.parseBoolean(this.cbxPermisoSensores.getSelectedItem().toString()),
                Boolean.parseBoolean(this.cbxPermisoDatoSensor.getSelectedItem().toString()),
                Boolean.parseBoolean(this.cbxPermisoDatosEnVivo.getSelectedItem().toString()),
                Boolean.parseBoolean(this.cbxPermisoDatosUsuario.getSelectedItem().toString()),
                Boolean.parseBoolean(this.cbxPermisoDatosRol.getSelectedItem().toString()),
                Boolean.parseBoolean(this.cbxPermisoReportes.getSelectedItem().toString())
        );
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxPermisoDatoSensor;
    private javax.swing.JComboBox<String> cbxPermisoDatosEnVivo;
    private javax.swing.JComboBox<String> cbxPermisoDatosRol;
    private javax.swing.JComboBox<String> cbxPermisoDatosUsuario;
    private javax.swing.JComboBox<String> cbxPermisoReportes;
    private javax.swing.JComboBox<String> cbxPermisoSensores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
