/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.jefte.estacionmeteorologica.Roles;

import com.fasterxml.jackson.core.type.TypeReference;
import com.jefte.estacionmeteorologica.ManejoArchivos.JsonHandler;
import java.util.Map;
import javax.swing.JCheckBox;

/**
 *
 * @author Brandon Campos
 */
public class GUIBuscarRol extends javax.swing.JDialog {

    /**
     * Creates new form GUIBuscarRol
     */
    private boolean edicion;
    private boolean confirmar;
    private JsonHandler<Rol> gestionRol;
    private String[] datos = {"","","","","",""};

    public GUIBuscarRol(java.awt.Frame parent, boolean modal, String nombreJson) {
        super(parent, modal);
        this.gestionRol = new JsonHandler(nombreJson, new TypeReference<Map<Integer, Rol>>() {
        });

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        cbxPermisoReportes = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        ckReportes = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cbxPermisoDatosRol = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ckRol = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cbxPermisoDatosUsuario = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ckUsuario = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cbxPermisoDatosEnVivo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ckVivo = new javax.swing.JCheckBox();
        cbxPermisoDatoSensor = new javax.swing.JComboBox<>();
        ckDatosSensores = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ckSensores = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbxPermisoSensores = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Filtrar");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, 30));

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Volver");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, 30));

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (8).png"))); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.setBorder(null);
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 115, 50));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (8).png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 103, 50));

        cbxPermisoReportes.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoReportes.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "false", "true" }));
        cbxPermisoReportes.setBorder(null);
        cbxPermisoReportes.setEnabled(false);
        jPanel2.add(cbxPermisoReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 402, 260, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 300, 50));

        ckReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckReportesActionPerformed(evt);
            }
        });
        jPanel2.add(ckReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reportes:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 94, -1));

        cbxPermisoDatosRol.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoDatosRol.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoDatosRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "false", "true" }));
        cbxPermisoDatosRol.setBorder(null);
        cbxPermisoDatosRol.setEnabled(false);
        cbxPermisoDatosRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPermisoDatosRolActionPerformed(evt);
            }
        });
        jPanel2.add(cbxPermisoDatosRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 250, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 300, 50));

        ckRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckRolActionPerformed(evt);
            }
        });
        jPanel2.add(ckRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Datos Rol: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 94, -1));

        cbxPermisoDatosUsuario.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoDatosUsuario.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoDatosUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "false", "true" }));
        cbxPermisoDatosUsuario.setBorder(null);
        cbxPermisoDatosUsuario.setEnabled(false);
        jPanel2.add(cbxPermisoDatosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 260, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 300, 50));

        ckUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(ckUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Datos Usuario:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, -1));

        cbxPermisoDatosEnVivo.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoDatosEnVivo.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoDatosEnVivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "false", "true" }));
        cbxPermisoDatosEnVivo.setBorder(null);
        cbxPermisoDatosEnVivo.setEnabled(false);
        jPanel2.add(cbxPermisoDatosEnVivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 260, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 300, 50));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Datos en Vivo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, -1));

        ckVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckVivoActionPerformed(evt);
            }
        });
        jPanel2.add(ckVivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        cbxPermisoDatoSensor.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoDatoSensor.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoDatoSensor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "false", "true" }));
        cbxPermisoDatoSensor.setBorder(null);
        cbxPermisoDatoSensor.setEnabled(false);
        cbxPermisoDatoSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPermisoDatoSensorActionPerformed(evt);
            }
        });
        jPanel2.add(cbxPermisoDatoSensor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 102, 260, 30));

        ckDatosSensores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckDatosSensoresActionPerformed(evt);
            }
        });
        jPanel2.add(ckDatosSensores, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos Sensores:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 300, 50));

        ckSensores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSensoresActionPerformed(evt);
            }
        });
        jPanel2.add(ckSensores, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sensores:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 94, -1));

        cbxPermisoSensores.setBackground(new java.awt.Color(240, 237, 255));
        cbxPermisoSensores.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cbxPermisoSensores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "false", "true" }));
        cbxPermisoSensores.setBorder(null);
        cbxPermisoSensores.setEnabled(false);
        jPanel2.add(cbxPermisoSensores, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 260, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BrandonImagen.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 300, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image (7).png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, 500, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbxPermisoDatosRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPermisoDatosRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPermisoDatosRolActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        datos[0] = (this.cbxPermisoSensores.isEnabled()) ? this.cbxPermisoSensores.getSelectedItem().toString() : "";
        datos[1] = (this.cbxPermisoDatoSensor.isEnabled()) ? this.cbxPermisoDatoSensor.getSelectedItem().toString() : "";
        datos[2] = (this.cbxPermisoDatosEnVivo.isEnabled()) ? this.cbxPermisoDatosEnVivo.getSelectedItem().toString() : "";
        datos[3] = (this.cbxPermisoDatosRol.isEnabled()) ? this.cbxPermisoDatosRol.getSelectedItem().toString() : "";
        datos[4] = (this.cbxPermisoReportes.isEnabled()) ? this.cbxPermisoReportes.getSelectedItem().toString() : "";
        datos[5] = (this.cbxPermisoDatosUsuario.isEnabled()) ? this.cbxPermisoDatosUsuario.getSelectedItem().toString() : "";
        this.confirmar = true;
        this.setVisible(false);
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    public Boolean getCkDatosSensores() {
        return ckDatosSensores.isSelected();
    }

    public Boolean getCkReportes() {
        return ckReportes.isSelected();
    }

    public Boolean getCkRol() {
        return ckRol.isSelected();
    }

    public Boolean getCkSensores() {
        return ckSensores.isSelected();
    }

    public Boolean getCkUsuario() {
        return ckUsuario.isSelected();
    }

    public Boolean getCkVivo() {
        return ckVivo.isSelected();
    }

    private void cbxPermisoDatoSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPermisoDatoSensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPermisoDatoSensorActionPerformed

    private void ckSensoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSensoresActionPerformed
        this.cbxPermisoSensores.setEnabled((this.cbxPermisoSensores.isEnabled()) ? false : true);
    }//GEN-LAST:event_ckSensoresActionPerformed

    private void ckDatosSensoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckDatosSensoresActionPerformed
        this.cbxPermisoDatoSensor.setEnabled((this.cbxPermisoDatoSensor.isEnabled()) ? false : true);
    }//GEN-LAST:event_ckDatosSensoresActionPerformed

    private void ckVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckVivoActionPerformed
        this.cbxPermisoDatosEnVivo.setEnabled((this.cbxPermisoDatosEnVivo.isEnabled()) ? false : true);
    }//GEN-LAST:event_ckVivoActionPerformed

    private void ckUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckUsuarioActionPerformed
        this.cbxPermisoDatosUsuario.setEnabled((this.cbxPermisoDatosUsuario.isEnabled()) ? false : true);
    }//GEN-LAST:event_ckUsuarioActionPerformed

    private void ckRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckRolActionPerformed
        this.cbxPermisoDatosRol.setEnabled((this.cbxPermisoDatosRol.isEnabled()) ? false : true);
    }//GEN-LAST:event_ckRolActionPerformed

    private void ckReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckReportesActionPerformed
       this.cbxPermisoReportes.setEnabled((this.cbxPermisoReportes.isEnabled()) ? false : true);
    }//GEN-LAST:event_ckReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public String obtenerDatos(int indice) {
        return datos[indice];
    }
     public boolean confirmacion() {

        return this.confirmar;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxPermisoDatoSensor;
    private javax.swing.JComboBox<String> cbxPermisoDatosEnVivo;
    private javax.swing.JComboBox<String> cbxPermisoDatosRol;
    private javax.swing.JComboBox<String> cbxPermisoDatosUsuario;
    private javax.swing.JComboBox<String> cbxPermisoReportes;
    private javax.swing.JComboBox<String> cbxPermisoSensores;
    private javax.swing.JCheckBox ckDatosSensores;
    private javax.swing.JCheckBox ckReportes;
    private javax.swing.JCheckBox ckRol;
    private javax.swing.JCheckBox ckSensores;
    private javax.swing.JCheckBox ckUsuario;
    private javax.swing.JCheckBox ckVivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
