/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jefte.estacionmeteorologica.Auth;

import com.jefte.estacionmeteorologica.ManejoArchivos.JsonHandler;

/**
 *
 * @author Brandon Campos
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIAdministrador
     */
    //private JsonHandler<Rol> gestionRol;
      private String nombreJson = "roles.json";
    public GUIMenu(int id_Rol) {
        initComponents();
        
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSensores = new javax.swing.JButton();
        btnDatosSensores = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnReportesEnVivo = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnRoles = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSensores.setText("Sensores");
        btnSensores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSensoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnSensores, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 132, 34));

        btnDatosSensores.setText("Datos Sensores");
        jPanel1.add(btnDatosSensores, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, 46));

        btnReportes.setText("Reportes");
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 136, -1));

        btnReportesEnVivo.setText("Reportes en vivo");
        jPanel1.add(btnReportesEnVivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, 46));

        btnUsuario.setText("Usuario");
        jPanel1.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 650, -1, -1));

        btnRoles.setText("Roles");
        jPanel1.add(btnRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondoMenu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1285, 728));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSensoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSensoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSensoresActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatosSensores;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReportesEnVivo;
    private javax.swing.JButton btnRoles;
    private javax.swing.JButton btnSensores;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
