/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jefte.estacionmeteorologica.Auth;

import com.fasterxml.jackson.core.type.TypeReference;
import com.jefte.estacionmeteorologica.ManejoArchivos.JsonHandler;
import com.jefte.estacionmeteorologica.Usuarios.Usuario;
import com.jefte.estacionmeteorologica.Validaciones.Validar;
import java.awt.Color;
import java.util.Map;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Brandon Campos
 */
public class GUIRegistro extends javax.swing.JFrame {

  private JsonHandler<Usuario> gestionUsuario;
  private String nombreJson = "Usuarios.json";
  private boolean[] checks = { false, false, false, false, false, false };

  public GUIRegistro() {
    initComponents();
    this.gestionUsuario = new JsonHandler(nombreJson, new TypeReference<Map<Integer, Usuario>>() {
    });

  }

  private boolean isCheck() {
    if (checks[0] && checks[1] && checks[2] && checks[3] && checks[4] && checks[5]) {
      return true;
    }
    return false;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    lblCorreo = new javax.swing.JLabel();
    txtCorreoElectronico = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    lblNombre = new javax.swing.JLabel();
    txtNombre = new javax.swing.JTextField();
    lblContraseña = new javax.swing.JLabel();
    txtContraseña = new javax.swing.JTextField();
    btnRegistrarse = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();
    lblPApellido = new javax.swing.JLabel();
    txtPApellido = new javax.swing.JTextField();
    lblSApellido = new javax.swing.JLabel();
    txtSApellido = new javax.swing.JTextField();
    lblCedula = new javax.swing.JLabel();
    txtCedula = new javax.swing.JTextField();
    lblIniciarSesion = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblCorreo.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    lblCorreo.setForeground(new java.awt.Color(0, 0, 0));
    lblCorreo.setText("Correo Electronico");
    jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

    txtCorreoElectronico.setBackground(new java.awt.Color(240, 237, 255));
    txtCorreoElectronico.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    txtCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));
    txtCorreoElectronico.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    txtCorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtCorreoElectronicoKeyReleased(evt);
      }
    });
    jPanel1.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 270, 30));

    jLabel7.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/usuario.png"))); // NOI18N
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

    lblNombre.setBackground(new java.awt.Color(0, 0, 0));
    lblNombre.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    lblNombre.setForeground(new java.awt.Color(0, 0, 0));
    lblNombre.setText("Nombre");
    jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

    txtNombre.setBackground(new java.awt.Color(240, 237, 255));
    txtNombre.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    txtNombre.setForeground(new java.awt.Color(0, 0, 0));
    txtNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtNombreKeyReleased(evt);
      }
    });
    jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 270, 30));

    lblContraseña.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    lblContraseña.setForeground(new java.awt.Color(0, 0, 0));
    lblContraseña.setText("Contraseña");
    jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 120, -1));

    txtContraseña.setBackground(new java.awt.Color(240, 237, 255));
    txtContraseña.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    txtContraseña.setForeground(new java.awt.Color(0, 0, 0));
    txtContraseña.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtContraseñaKeyReleased(evt);
      }
    });
    jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 270, 30));

    btnRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("./assets/registrarme.png"))); // NOI18N
    btnRegistrarse.setEnabled(false);
    btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegistrarseActionPerformed(evt);
      }
    });
    jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 150, 70));

    btnCancelar.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/cancelar.png"))); // NOI18N
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });
    jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 130, 70));

    lblPApellido.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    lblPApellido.setForeground(new java.awt.Color(0, 0, 0));
    lblPApellido.setText("Primer Apellido");
    jPanel1.add(lblPApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

    txtPApellido.setBackground(new java.awt.Color(240, 237, 255));
    txtPApellido.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    txtPApellido.setForeground(new java.awt.Color(0, 0, 0));
    txtPApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    txtPApellido.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtPApellidoActionPerformed(evt);
      }
    });
    txtPApellido.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtPApellidoKeyReleased(evt);
      }
    });
    jPanel1.add(txtPApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 280, 30));

    lblSApellido.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    lblSApellido.setForeground(new java.awt.Color(0, 0, 0));
    lblSApellido.setText("Segundo Apellido");
    jPanel1.add(lblSApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

    txtSApellido.setBackground(new java.awt.Color(240, 237, 255));
    txtSApellido.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    txtSApellido.setForeground(new java.awt.Color(0, 0, 0));
    txtSApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    txtSApellido.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtSApellidoKeyReleased(evt);
      }
    });
    jPanel1.add(txtSApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 280, 30));

    lblCedula.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
    lblCedula.setForeground(new java.awt.Color(0, 0, 0));
    lblCedula.setText("Cedula");
    jPanel1.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

    txtCedula.setBackground(new java.awt.Color(240, 237, 255));
    txtCedula.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    txtCedula.setForeground(new java.awt.Color(0, 0, 0));
    txtCedula.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtCedulaKeyReleased(evt);
      }
    });
    jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 270, 30));

    lblIniciarSesion.setFont(new java.awt.Font("Poppins", 1, 30)); // NOI18N
    lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
    lblIniciarSesion.setText("REGISTRO");
    jPanel1.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

    jLabel15.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/contraseña.png"))); // NOI18N
    jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

    jLabel20.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/txtField2.png"))); // NOI18N
    jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

    jLabel4.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/cedula.png"))); // NOI18N
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

    jLabel18.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/txtField2.png"))); // NOI18N
    jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

    jLabel1.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/cedula.png"))); // NOI18N
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

    jLabel9.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/usuario.png"))); // NOI18N
    jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

    jLabel16.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/txtField2.png"))); // NOI18N
    jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

    jLabel12.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/txtField2.png"))); // NOI18N
    jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

    jLabel6.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(82, 82, 82));
    jLabel6.setText("Ingrese su información para registrarse");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

    jLabel8.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/usuario.png"))); // NOI18N
    jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

    jLabel11.setForeground(new java.awt.Color(240, 237, 255));
    jLabel11.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/txtField2.png"))); // NOI18N
    jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

    jLabel10.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/txtField2.png"))); // NOI18N
    jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

    jLabel2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/fondoRegister.png"))); // NOI18N
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

    jLabel13.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/txtField.png"))); // NOI18N
    jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

    jLabel14.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/usuario.png"))); // NOI18N
    jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

    jLabel17.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/txtField2.png"))); // NOI18N
    jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

    jLabel3.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/cedula.png"))); // NOI18N
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

    jLabel19.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/txtField2.png"))); // NOI18N
    jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

    jLabel5.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/com/jefte/estacionmeteorologica/assets/cedula.png"))); // NOI18N
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistrarseActionPerformed
    boolean valido = true;
    for (Usuario usuario : gestionUsuario.obtenerDatos().values()) {
      if (usuario.getCorreo_electronico().equals(this.txtCorreoElectronico.getText())) {
        valido = false;
        JOptionPane.showMessageDialog(null, "El correo ya se encuentra en uso.");
      }

      if (String.valueOf(usuario.getCedula()).equals(this.txtCedula.getText())) {
        valido = false;
        JOptionPane.showMessageDialog(null, "El numero de cedula ya se encuentra registrado.");
      }

    }

    if (valido) {
      this.gestionUsuario.agregar(new Usuario(this.gestionUsuario.obtenerUltimoId() + 1,
          Integer.parseInt(this.txtCedula.getText()), this.txtNombre.getText(), this.txtPApellido.getText(),
          this.txtSApellido.getText(), this.txtCorreoElectronico.getText(), this.txtContraseña.getText()));
      JOptionPane.showMessageDialog(null, "Usuario Registrado existosamente!");
      this.dispose();
      GUILogin.initGUI();
    }

  }// GEN-LAST:event_btnRegistrarseActionPerformed

  private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNombreKeyReleased
    if (Validar.validaciones(this.txtNombre.getText(), "[a-zA-Z]+")) {
      this.lblNombre.setForeground(Color.black);
      this.checks[0] = true;
    } else {
      this.checks[0] = false;
      this.lblNombre.setForeground(Color.red);
    }
    this.btnRegistrarse.setEnabled(isCheck());
  }// GEN-LAST:event_txtNombreKeyReleased

  private void txtPApellidoKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtPApellidoKeyReleased
    if (Validar.validaciones(this.txtPApellido.getText(), "[a-zA-Z]+")) {
      this.lblPApellido.setForeground(Color.black);
      this.checks[1] = true;
    } else {
      this.checks[1] = false;
      this.lblPApellido.setForeground(Color.red);
    }
    this.btnRegistrarse.setEnabled(isCheck());
  }// GEN-LAST:event_txtPApellidoKeyReleased

  private void txtSApellidoKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtSApellidoKeyReleased

    if (Validar.validaciones(this.txtSApellido.getText(), "[a-zA-Z]+")) {
      this.lblSApellido.setForeground(Color.black);
      this.checks[2] = true;
    } else {
      this.checks[2] = false;
      this.lblSApellido.setForeground(Color.red);
    }
    this.btnRegistrarse.setEnabled(isCheck());

  }// GEN-LAST:event_txtSApellidoKeyReleased

  private void txtCorreoElectronicoKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtCorreoElectronicoKeyReleased
    if (Validar.validaciones(this.txtCorreoElectronico.getText(),
        "[A-Za-z0-9\\._%+\\-]+@[A-Za-z0-9\\.\\-]+\\.[A-Za-z]{2,}")) {
      this.lblCorreo.setForeground(Color.black);
      this.checks[3] = true;
    } else {
      this.checks[3] = false;
      this.lblCorreo.setForeground(Color.red);
    }
    this.btnRegistrarse.setEnabled(isCheck());
  }// GEN-LAST:event_txtCorreoElectronicoKeyReleased

  private void txtContraseñaKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtContraseñaKeyReleased
    if (Validar.validaciones(this.txtContraseña.getText(), "[\\S]+")) {
      this.lblContraseña.setForeground(Color.black);
      this.checks[4] = true;
    } else {
      this.checks[4] = false;
      this.lblContraseña.setForeground(Color.red);
    }
    this.btnRegistrarse.setEnabled(isCheck());
  }// GEN-LAST:event_txtContraseñaKeyReleased

  private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtCedulaKeyReleased
    if (Validar.validaciones(this.txtCedula.getText(), "[0-9]{9}")) {
      this.lblCedula.setForeground(Color.black);
      this.checks[5] = true;
    } else {
      this.checks[5] = false;
      this.lblCedula.setForeground(Color.red);
    }
    this.btnRegistrarse.setEnabled(isCheck());
  }// GEN-LAST:event_txtCedulaKeyReleased

  private void txtPApellidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPApellidoActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtPApellidoActionPerformed

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
    this.dispose();
    GUILogin.initGUI();
  }// GEN-LAST:event_btnCancelarActionPerformed

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnRegistrarse;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lblCedula;
  private javax.swing.JLabel lblContraseña;
  private javax.swing.JLabel lblCorreo;
  private javax.swing.JLabel lblIniciarSesion;
  private javax.swing.JLabel lblNombre;
  private javax.swing.JLabel lblPApellido;
  private javax.swing.JLabel lblSApellido;
  private javax.swing.JTextField txtCedula;
  private javax.swing.JTextField txtContraseña;
  private javax.swing.JTextField txtCorreoElectronico;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JTextField txtPApellido;
  private javax.swing.JTextField txtSApellido;
  // End of variables declaration//GEN-END:variables
}
